### ISSUE TITLE
Add majifix deployment checklist

### ISSUE THREAD

**Issue by BenMaruchu** [CodeTanzania/majifix-docs#3]
This should be  guide for anyone who wish to deploy majifix. The list should be comprehensive and cover all the details needed for deployment.
- [ ] Should cover server requirements i.e RAM, Storage e.t.c
- [ ] Should cover technologies( dependencies) that should be installed prior to deployment
- [ ] Should cover how to backup the system db
- [ ] Should cover what is the default login configurations
